version: '3'

services:
  redis:
    image: 'redislabs/redisearch:latest'
  backend:
    build:
      dockerfile: Dockerfile
      context: .
    environment:
      - REDIS_HOST=redis
    ports:
      - '3000:3000'